/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 학생 회원가입 (이메일·비밀번호) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        university: string;
                        major: string;
                        year_in_school: number;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user_id?: number;
                            email_verification_sent?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일·비밀번호 로그인 (JWT 발급) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 로그인 성공 (refresh는 HttpOnly 쿠키로 별도 설정) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            /** @description 초 */
                            expires_in?: number;
                            role?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** refresh 토큰으로 access 재발급 (refresh 회전) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            expires_in?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** refresh 토큰 무효화 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description no content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    code: string;
                };
                header?: never;
                path: {
                    provider: "google" | "naver";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 클라이언트 URL로 리다이렉트 + 쿠키 설정 */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 학생 프로필 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentProfile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 내 학생 프로필 업데이트 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        university?: string;
                        major?: string;
                        year_in_school?: number;
                        /** Format: date */
                        expected_grad_at?: string | null;
                    };
                };
            };
            responses: {
                /** @description updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentProfile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/students/me/target-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TargetJob"][];
                    };
                };
            };
        };
        /** 목표 직무 일괄 갱신 (최대 3개) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        industry_code: string;
                        job_role_code: string;
                        priority: number;
                    }[];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 활동 목록 조회 */
        get: {
            parameters: {
                query?: {
                    category?: "course" | "project" | "club" | "volunteer" | "contest" | "external" | "internship" | "award" | "certification";
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pagination?: components["schemas"]["Pagination"];
                            items?: components["schemas"]["Activity"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 활동 등록 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActivityInput"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Activity"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActivityInput"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Activity"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/gap-diagnosis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 갭 진단 계산 트리거 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        target_job_id: number;
                    };
                };
            };
            responses: {
                /** @description 진단 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GapDiagnosis"];
                    };
                };
                /** @description 필수 프로필 누락 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gap-diagnosis/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    target_job_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 최신 진단 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GapDiagnosis"];
                    };
                };
                /** @description 진단 이력 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 활성 로드맵 조회 */
        get: {
            parameters: {
                query: {
                    target_job_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Roadmap"];
                    };
                };
            };
        };
        put?: never;
        /** 로드맵 (재)생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        target_job_id: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Roadmap"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmap/items/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /** 로드맵 항목 상태 변경 (완료·진행·건너뜀) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "pending" | "in_progress" | "done" | "skipped";
                        /** @description skipped/reject 시 사유 (FR-014 거부 학습) */
                        feedback_reason?: string | null;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoadmapItem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    doc_type?: "resume" | "cover_letter" | "portfolio";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeneratedDocument"][];
                    };
                };
            };
        };
        put?: never;
        /** 문서 자동 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        doc_type: "resume" | "cover_letter" | "portfolio";
                        template_code: string;
                        /** Format: int64 */
                        target_job_id?: number | null;
                        /** @description cover_letter 항목별 키워드 */
                        cover_letter_prompts?: string[];
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeneratedDocument"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 내보내기 (PDF 또는 공유 링크) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        format: "pdf" | "share_link";
                        /** @default 168 */
                        expires_in_hours?: number;
                        view_limit?: number | null;
                    };
                };
            };
            responses: {
                /** @description 내보내기 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pdf_url?: string;
                        } | components["schemas"]["DocumentShareLink"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            email_enabled?: boolean;
                            inapp_enabled?: boolean;
                            /** @enum {string} */
                            digest_frequency?: "daily" | "weekly" | "per_event";
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email_enabled?: boolean;
                        inapp_enabled?: boolean;
                        /** @enum {string} */
                        digest_frequency?: "daily" | "weekly" | "per_event";
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pagination?: components["schemas"]["Pagination"];
                            items?: {
                                id?: number;
                                template_code?: string;
                                payload?: Record<string, never>;
                                /** Format: date-time */
                                sent_at?: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 미션 목록 (학생용; P3) */
        get: {
            parameters: {
                query?: {
                    industry_code?: string;
                    job_role_code?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 미션 제출 (P3) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description 제출 큐 적재 + AI 1차 분석 시작 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결제 시작 (P4 — PortOne) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        plan_code: string;
                        pay_method?: string;
                    };
                };
            };
            responses: {
                /** @description 결제 페이지 또는 PortOne 토큰 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            imp_uid?: string;
                            merchant_uid?: string;
                            amount_krw?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook/portone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** PortOne 결제 결과 웹훅 (멱등 처리) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/universities/dashboard/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 대학 관리자 — 집계 통계 (R-7, scope=university:aggregate)
         * @description 학과·학년·코호트 단위의 집계 통계만 반환한다. 셀별 인원 수가 k=5 미만이면
         *     해당 셀은 자동 마스킹된다. 학생 개인 식별 정보는 절대 포함하지 않는다.
         *     scope=university:aggregate 권한이 있으면 학생측 차등 동의 여부와 무관하게 조회 가능.
         */
        get: {
            parameters: {
                query?: {
                    department?: string;
                    year_in_school?: number;
                    cohort_year?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 집계 통계 (k-익명성 자동 적용) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            generated_at?: string;
                            rows?: {
                                /** @description 예: 경영학과/3학년 */
                                bucket?: string;
                                /** @description k<5는 null로 마스킹 */
                                student_count?: number;
                                /** Format: float */
                                avg_roadmap_completion?: number | null;
                                /** Format: float */
                                avg_gap_score?: number | null;
                                /** Format: float */
                                avg_active_days_30d?: number | null;
                            }[];
                        };
                    };
                };
                /** @description scope 부족 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/universities/students/{studentId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 대학 관리자 — 개인 단위 진척도 (R-7, scope=university:individual + 학생 동의 필요)
         * @description 다음 3개 조건을 모두 만족할 때만 200을 반환한다 — (1) 호출자 JWT가
         *     scope=university:individual 보유, (2) students.university_consent_scope='individual',
         *     (3) students.university_id = admin.university_id. 응답 시 audit_logs에
         *     action='university_view_individual' 강제 적재.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    studentId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 학생 개인 단위 진척도 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: int64 */
                            student_id?: number;
                            name?: string;
                            major?: string;
                            year_in_school?: number;
                            /** Format: float */
                            roadmap_completion?: number;
                            recent_activities?: Record<string, never>[];
                            /** Format: date-time */
                            generated_at?: string;
                        };
                    };
                };
                /** @description scope 부족 또는 대학 ID 불일치 또는 학생 동의 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 학생 미존재 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/me/university-consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 대학 측 진척도 노출 범위 토글 (R-7 차등 동의) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description none = 대학에 어떤 데이터도 제공 안 함
                         *     aggregate_only = 집계 통계에만 포함(개인 식별 불가)
                         *     individual = 개인 단위 조회까지 허용
                         * @enum {string}
                         */
                        scope: "none" | "aggregate_only" | "individual";
                    };
                };
            };
            responses: {
                /** @description 동의 범위 변경 완료. consent_records에 새 행 추가됨 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/mentor/me/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 멘토 현재 트랙 및 변경 가능 시점 조회 (R-8) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            mentor_track?: "fixed" | "commission";
                            /** Format: date-time */
                            track_changed_at?: string | null;
                            /**
                             * Format: date-time
                             * @description 분기당 1회 쿨다운
                             */
                            next_change_eligible_at?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 멘토 트랙 변경 (R-8, 90일 쿨다운 적용) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        to_track: "fixed" | "commission";
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description 변경 완료 (mentor_track_history 적재) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 쿨다운 미경과 (next_change_eligible_at 포함) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/mentor/me/payment-method": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 멘토 정산 계좌·사업자 정보 등록·갱신 (R-8) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        bank_code: string;
                        account_no: string;
                        account_holder: string;
                        /** @description 개인사업자만 */
                        business_no?: string | null;
                        is_business?: boolean;
                    };
                };
            };
            responses: {
                /** @description 저장 완료. 1원 인증 트리거됨 (verified_at은 별도 확인 후 갱신) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentor/me/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 멘토 월 정산 내역 조회 (R-8) */
        get: {
            parameters: {
                query?: {
                    year?: number;
                    month?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 정산 내역 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            period_year?: number;
                            period_month?: number;
                            /** @enum {string} */
                            track?: "fixed" | "commission";
                            gross_krw?: number;
                            withholding_krw?: number;
                            net_krw?: number;
                            /** @enum {string} */
                            status?: "pending" | "approved" | "paid" | "failed";
                            /** Format: date-time */
                            paid_at?: string | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 모바일 디바이스 푸시 토큰 등록 (R-6) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        platform: "ios" | "android" | "web";
                        device_token: string;
                        app_version?: string | null;
                        os_version?: string | null;
                    };
                };
            };
            responses: {
                /** @description 토큰 등록. 기존 (platform */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/push-tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 푸시 토큰 비활성화 (로그아웃·앱 삭제 시) (R-6) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tokenId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deactivated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/enterprises/job-postings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 기업 직무 등록 (P4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        industry_code: string;
                        job_role_code: string;
                        /** Format: date */
                        open_at: string;
                        /** Format: date */
                        close_at: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/enterprises/contact-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 익명 학생에 컨택 요청 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 매칭 결과의 익명 핸들 */
                        student_handle: string;
                        /** Format: int64 */
                        job_posting_id: number;
                        message: string;
                    };
                };
            };
            responses: {
                /** @description 학생에게 알림 발송 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/moderation-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영자 검수 큐 조회 */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "approved" | "rejected";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/me/data-export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 학생 개인정보 일괄 내보내기 요청 (FR-004)
         * @description 비동기 잡 enqueue. 완료 시 이메일로 7일 유효 다운로드 URL 발송.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: int64 */
                            request_id?: number;
                            /** @enum {string} */
                            status?: "pending" | "processing" | "ready" | "expired";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/me/data-export/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내보내기 요청 상태·다운로드 URL 조회 (FR-004) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "pending" | "processing" | "ready" | "expired";
                            download_url?: string | null;
                            /** Format: date-time */
                            expires_at?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/me/account-deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 학생 탈퇴 요청 — 30일 유예 시작 (FR-004) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 탈퇴 요청 취소 (유예 기간 내) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description canceled */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동의 5종 현재 상태 + 시점 이력 (FR-031) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            categories?: {
                                /** @enum {string} */
                                code?: "service_use" | "university_share" | "enterprise_share" | "anonymous_dataset" | "marketing";
                                granted?: boolean;
                                /** @description university_share 전용: none/aggregate_only/individual */
                                scope?: string | null;
                                /** Format: date-time */
                                last_changed_at?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 동의 5종 부분 갱신 (FR-031) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string|null} */
                        university_share?: "none" | "aggregate_only" | "individual" | null;
                        enterprise_share?: boolean | null;
                        anonymous_dataset?: boolean | null;
                        marketing?: boolean | null;
                    };
                };
            };
            responses: {
                /** @description 부분 갱신 완료. 각 항목마다 consent_records에 새 행 적재 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/students/me/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 학생 정기 리포트 목록 (FR-026/028) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: int64 */
                            id?: number;
                            /** @enum {string} */
                            period_kind?: "quarterly" | "semester_end" | "year_end";
                            /** Format: date */
                            period_end?: string;
                            /** Format: date-time */
                            sent_at?: string | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/me/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 정기 리포트 상세 (FR-028) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 리포트 페이로드 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/enterprises/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 채용 성사 신고 (FR-040 — 학생·기업 양측 보고) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        student_id: number;
                        /** Format: int64 */
                        enterprise_id: number;
                        /** Format: int64 */
                        job_posting_id?: number | null;
                        /** Format: date */
                        start_date: string;
                        salary_krw?: number | null;
                        /** @enum {string} */
                        contract_kind: "full_time" | "internship" | "contract";
                    };
                };
            };
            responses: {
                /** @description 보고 접수. 양측 컨펌 시 자동 확정 + enterprise_billings draft 생성 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: int64 */
                            placement_id?: number;
                            /** @enum {string} */
                            status?: "pending" | "confirmed" | "canceled";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/enterprises/placements/{placementId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 채용 성사 취소·환급 (90일 내, 운영자 검수) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    placementId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description 운영자 검수 대기 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/enterprises/billings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기업 청구서 목록 (FR-040) */
        get: {
            parameters: {
                query?: {
                    status?: "draft" | "issued" | "paid" | "refunded";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/senior/contributions/me/rewards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 선배 기부자 인센티브 내역·뱃지 (FR-046) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cash_total_krw?: number;
                            credit_balance?: number;
                            badges?: string[];
                            ledger?: {
                                /** @enum {string} */
                                kind?: "cash" | "credit" | "badge";
                                amount_krw?: number | null;
                                credit_units?: number | null;
                                badge_code?: string | null;
                                reason?: string;
                                /** Format: date-time */
                                accrued_at?: string;
                                /** Format: date-time */
                                settled_at?: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영자용 SC-001~SC-020 KPI 대시보드 데이터 (C5) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description SC-001..SC-020 */
                            sc_code?: string;
                            /** Format: float */
                            ratio_pct?: number;
                            numerator?: number;
                            denominator?: number;
                            /** Format: date */
                            snapshot_date?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 헬스 체크 (Liveness) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 의존성 확인 (Readiness) — DB·Redis·MinIO·외부 LLM */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 의존성 일부 사용 불가 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example VALIDATION_ERROR */
            code: string;
            message: string;
            details?: Record<string, never>;
        };
        Pagination: {
            page?: number;
            page_size?: number;
            total?: number;
        };
        StudentProfile: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            university: string;
            major: string;
            year_in_school: number;
            /** Format: date */
            expected_grad_at?: string | null;
            school_email_verified?: boolean;
        };
        TargetJob: {
            /** Format: int64 */
            id: number;
            industry_code: string;
            job_role_code: string;
            priority: number;
        };
        Activity: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            category: "course" | "project" | "club" | "volunteer" | "contest" | "external" | "internship" | "award" | "certification";
            title: string;
            description?: string | null;
            /** Format: date */
            started_at: string;
            /** Format: date */
            ended_at?: string | null;
            outcome?: string | null;
            tags?: {
                tag?: string;
                /** @enum {string} */
                source?: "auto" | "user";
                weight?: number | null;
            }[];
        };
        ActivityInput: {
            /** @enum {string} */
            category: "course" | "project" | "club" | "volunteer" | "contest" | "external" | "internship" | "award" | "certification";
            title: string;
            description?: string | null;
            /** Format: date */
            started_at: string;
            /** Format: date */
            ended_at?: string | null;
            outcome?: string | null;
            manual_tags?: string[];
        };
        GapDiagnosis: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            target_job_id: number;
            /** Format: date-time */
            computed_at: string;
            overall_score: number;
            payload: {
                fulfilled?: string[];
                missing?: string[];
                priority_to_improve?: string[];
            };
            model_version?: string;
        };
        RoadmapItem: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            recommend_type: "certification" | "contest" | "external" | "internship" | "project" | "course";
            title: string;
            /** @enum {string} */
            recommend_term: "3-1" | "3-2" | "4-1" | "4-2" | "vacation" | "any";
            priority_rank: number;
            /** @enum {string} */
            status: "pending" | "in_progress" | "done" | "skipped";
            rationale?: {
                matched_senior_count?: number;
                match_score?: number;
                sample_confidence?: number;
                notes?: string | null;
            } | null;
        };
        Roadmap: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            target_job_id: number;
            /** Format: date-time */
            generated_at: string;
            model_version?: string;
            items: components["schemas"]["RoadmapItem"][];
        };
        GeneratedDocument: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            doc_type: "resume" | "cover_letter" | "portfolio";
            template_code: string;
            /** Format: int64 */
            target_job_id?: number | null;
            file_url?: string | null;
            content?: Record<string, never>;
            /** Format: date-time */
            created_at: string;
        };
        DocumentShareLink: {
            token: string;
            /** Format: date-time */
            expires_at: string;
            view_limit?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
