/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alumni/success-experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 직무 코호트 표본 메타 조회(추천 근거용) */
        get: {
            parameters: {
                query: {
                    job_code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 코호트 표본 수·k 충족 여부 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CohortMeta"];
                    };
                };
            };
        };
        put?: never;
        /** 현직자·선배 합격 경험 등록(익명화 적재) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SuccessExperienceInput"];
                };
            };
            responses: {
                /** @description 등록 성공(PII 제거·코호트 적재) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessExperience"];
                    };
                };
                /** @description 입력 검증 실패 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmap/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로드맵 생성(같은 직무 코호트 표본 근거, 미달 시 일반 가이드 폴백) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        job_code: string;
                    };
                };
            };
            responses: {
                /** @description 추천 결과(근거·폴백 여부 포함) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoadmapResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 — 세션·토큰 무효화(클라이언트는 저장소 클리어 후 메인 이동) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 무효화 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 부팅 하이드레이션용 현재 세션 검증·유저 재조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 유효 세션 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionUser"];
                    };
                };
                /** @description 만료/무효 — 클라이언트 저장소 클리어 트리거 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 파트너 유형별 회원가입(역할 계정 발급) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartnerSignupInput"];
                };
            };
            responses: {
                /** @description 가입 접수/역할 계정 발급 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description partner_type별 양식 검증 실패 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 로그인 역할의 허용 메뉴 목록(내비게이션·가드 단일 출처) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 허용 메뉴 키 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            role?: string;
                            allowed_menu_keys?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/talent-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기업 인재 검색(산업·직무 드롭다운 코드 매칭) */
        get: {
            parameters: {
                query: {
                    industry_code: string;
                    job_code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 매칭 인재 목록(0건 시 빈 배열+조건 안내) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TalentMatch"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{missionId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 멘토 심층 코멘트 작성(학생 제출물에 연결) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    missionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        submission_id: string;
                        comment: string;
                    };
                };
            };
            responses: {
                /** @description 코멘트 등록(학생 화면 노출) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 대시보드 점수(데모 계정 포함, 입력 데이터 기반 산출) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 점수·지표 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardScore"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 활동·스펙 등록(기간 시작~종료) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActivityInput"];
                };
            };
            responses: {
                /** @description 등록 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description end_date < start_date 등 검증 실패 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{docType}/export-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문서 생성 입력 데이터(클라이언트 PDF/docx 생성용) — 빈 기록 시 안내 */
        get: {
            parameters: {
                query: {
                    format: "pdf" | "docx";
                };
                header?: never;
                path: {
                    docType: "resume" | "cover_letter" | "portfolio";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 활동·스펙 누적 데이터(문서 초안 입력) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentExportData"];
                    };
                };
                /** @description 활동 기록 없음 — 먼저 기록 안내 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결제(테스트모드/가상 시나리오) — 성공 시 등급 변경, 실패 시 팝업 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        plan_target: string;
                        /** @enum {string} */
                        mode: "sandbox" | "virtual";
                        /**
                         * @description 가상 시나리오 데모용
                         * @enum {string}
                         */
                        force_result?: "success" | "fail";
                    };
                };
            };
            responses: {
                /** @description 결제 결과(실거래 아님 표기) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 광고·제휴·채용 노출 목록(가입자 희망 산업·직무 맞춤·숨김 없음) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 직무 적합·동의 충족 노출 항목('광고/제휴' 표기) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Promotion"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessExperienceInput: {
            job_code: string;
            industry_code: string;
            admit_year: number;
            /** @description PII 제거 */
            resume_summary?: string;
            portfolio_highlights?: string[];
            skills?: string[];
            timeline: {
                term?: string;
                /** @enum {string} */
                type?: "certificate" | "contest" | "intern" | "project" | "club" | "volunteer";
                title?: string;
                /** Format: date */
                start_date?: string;
                /** Format: date */
                end_date?: string | null;
            }[];
        };
        SuccessExperience: components["schemas"]["SuccessExperienceInput"] & {
            id?: string;
            anonymized?: boolean;
            /** @enum {string} */
            reward_status?: "pending" | "granted";
        };
        CohortMeta: {
            job_code?: string;
            sample_count?: number;
            /** @description sample_count >= 5 */
            k_anonymity_met?: boolean;
        };
        RoadmapResult: {
            job_code?: string;
            /** @description false면 일반 가이드 폴백 */
            personalized?: boolean;
            /** @description 같은 직무 합격 선배 N명 경로 + 요구역량 비중 기반 */
            rationale?: string;
            items?: {
                term?: string;
                recommendation?: string;
            }[];
        };
        SessionUser: {
            user_id?: string;
            role?: string;
            name?: string;
        };
        PartnerSignupInput: {
            /** @enum {string} */
            partner_type: "university" | "company" | "mentor" | "edu_activity_platform";
            org_name: string;
            contact: string;
            /** @description partner_type별 추가 양식 필드 */
            extra?: Record<string, never>;
        };
        TalentMatch: {
            student_id?: string;
            job_code?: string;
            match_score?: number;
        };
        DashboardScore: {
            total_score?: number;
            breakdown?: {
                [key: string]: number;
            };
            is_demo?: boolean;
        };
        ActivityInput: {
            /** @description 수강/프로젝트/동아리/봉사/공모전/대외활동/자격증/수상/인턴/아르바이트 */
            category: string;
            title: string;
            /** Format: date */
            start_date: string;
            /**
             * Format: date
             * @description 진행중이면 null
             */
            end_date?: string | null;
        };
        DocumentExportData: {
            doc_type?: string;
            /** @enum {string} */
            format?: "pdf" | "docx";
            sections?: Record<string, never>[];
            source_activity_ids?: string[];
        };
        PaymentResult: {
            /** @enum {string} */
            result?: "success" | "fail";
            /** @description 항상 false (실거래 아님) */
            is_real?: boolean;
            from_tier?: string;
            /** @description 실패 시 불변 */
            to_tier?: string | null;
            message?: string;
        };
        Promotion: {
            id?: string;
            /** @enum {string} */
            placement_type?: "ad" | "affiliate" | "jobposting";
            /** @description 화면 '광고/제휴' 표기 */
            label?: string;
            title?: string;
            match_industry_code?: string;
            match_job_code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
